### ISSUE TITLE
Include apk in release section

### ISSUE THREAD

**Issue by rancidfrog** [naz013/my-day-todo#2]
Having apk in release section would be appreciated:
https://github.com/naz013/my-day-todo/releases

**Comment by naz013** [comment]
Since 1.0.4 release builds will be included.

**Comment by naz013** [comment]
Release builds attached to drafts cannot be updated from Play Store since Goolge sign builds with own keys.

**Comment by rancidfrog** [comment]
Thank you,
Side note, I have seen that some projects upload gplay versions apk
But having apk is what is important, especially for quick testing
